# Script enhanced by ATCorp NDSU capstone team
import functions
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

"""
This script is generated from SeleniumIDE.
It  1) Launches the Getting Started Lab
    2) Switches to Computer A
    3) Opens the Terminal
    4) Enters "ls" in the Terminal (not showing?)
    5) Ends the Lab
"""

class TestCYRINTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cYRINTest(self):
    # Test name: CYRINTest
    # Step # | name | target | value | comment

    # Prompts the user for next action
    functions.promptUser()
    # 1 | open | /mod/cyrin/view.php?id=166 |  | 
    self.driver.get("https://cyrin.atcorp.com/mod/cyrin/view.php?id=166")

    # Prompts the user for next action
    functions.promptUser()
    # 2 | setWindowSize | 1552x840 |  | 
    self.driver.set_window_size(1552, 840)

    # Prompts the user for next action
    functions.promptUser()
    # 3 | selectFrame | index=0 |  | 
    self.driver.switch_to.frame(0)

    # Prompts the user for next action
    functions.promptUser()
    # 4 | click | name=control |  | 
    self.driver.find_element(By.NAME, "control").click()

    # Prompts the user for next action
    functions.promptUser()
    # 5 | click | id=current-vm-name |  | 
    self.driver.find_element(By.ID, "current-vm-name").click()

    # Prompts the user for next action
    functions.promptUser()
    # 6 | click | id=machinestatus_Ubuntu2004Desktop-4000-0182-eba4edce-809a-3fe20a37e1aa |  | 
    self.driver.find_element(By.ID, "machinestatus_Ubuntu2004Desktop-4000-0182-eba4edce-809a-3fe20a37e1aa").click()

    # Prompts the user for next action
    functions.promptUser()
    # 7 | click | css=.exercise-page |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".exercise-page").click()

    # Prompts the user for next action
    functions.promptUser()
    # 8 | click | css=#btnEndExercise > span:nth-child(1) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#btnEndExercise > span:nth-child(1)").click()

    # Prompts the user for next action
    functions.promptUser()
    # 9 | click | id=btnConfirmEndExercise |  | 
    self.driver.find_element(By.ID, "btnConfirmEndExercise").click()

# Running the functions to run the test
testClass = TestCYRINTest()

testClass.setup_method("")
testClass.test_cYRINTest()
testClass.teardown_method("")