# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGolden():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_golden(self):
    # Test name: golden
    # Step # | name | target | value | comment
    # 1 | open | https://cyrin.atcorp.com/login/index.php |  | 
    self.driver.get("https://cyrin.atcorp.com/login/index.php")
    # 2 | setWindowSize |  |  | 
    self.driver.maximize_window()
    # 3 | click | id=username |  | 
    self.driver.find_element(By.ID, "username").click()
    # 4 | click | id=password |  | 
    self.driver.find_element(By.ID, "password").click()
    # 5 | click | id=loginbtn |  | 
    self.driver.find_element(By.ID, "loginbtn").click()
    # 6 | selectFrame | index=0 |  | 
    self.driver.switch_to.frame(0)
    # 7 | click | name=control |  | 
    self.driver.find_element(By.NAME, "control").click()
    # 8 | click | id=computersMenuButton |  | 
    self.driver.find_element(By.ID, "computersMenuButton").click()
    # 9 | click | id=machinestatus_Ubuntu2004Desktop-4000-0182-eba4edce-809a-3fe20a37e1aa |  | 
    self.driver.find_element(By.ID, "machinestatus_Ubuntu2004Desktop-4000-0182-eba4edce-809a-3fe20a37e1aa").click()
    # 10 | click | id=btnEndExercise |  | 
    self.driver.find_element(By.ID, "btnEndExercise").click()
    # 11 | click | id=btnConfirmEndExercise |  | 
    self.driver.find_element(By.ID, "btnConfirmEndExercise").click()
  
